token = "BOT TOKEN HERE"
owners = [ 141231597155385344, ]
default_prefix = "!"  # The prefix for the bot's commands

[command_data]
guild_invite = ""
github = ""

[database]  # All this data is passed over to asyncpg
user = "DATABSE USERNAME"
password = "DATABASE PASSWORD"
database = "DATABASE NAME"
host = "127.0.0.1"
port = 5432

[presence]
text = "Game playing text"
activity_type = "playing"  # Should be one of 'playing', 'listening', 'watching'
status = "online"  # Should be one of 'online', 'invisible', 'idle', 'dnd'

[oauth]
client_id = ""
client_secret = ""
